### ISSUE TITLE
Banco de pautas 20 a 22/03

### ISSUE THREAD

**Issue by dina-matias** [Mutirao/EmRede#7]
- [x] Quarta | 20/03: PHP com Rapadura Quixadá/agenda no interior

- [x] Quinta | 21.03: Cripto.Baião

- [x] Sexta| 22/03: Open Data Day (É amanhã)

**Comment by uira** [comment]
@dinamatias7 Vamos estabelecer o protocolo de sempre subirmos esses eventos no Mapas também, pra começarmos a construir de fato essa Agenda Hacker

**Comment by dina-matias** [comment]
Todos publicados
