### ISSUE TITLE
Banco de Pautas 27 a 29/03

### ISSUE THREAD

**Issue by dina-matias** [Mutirao/EmRede#8]
- [x] 27/03 | Debate sobre proteção de dados pessoais na Internet

- [x] 28/03 | Cripto.Baião (flyers dos debates e oficinas) (https://www.facebook.com/events/2052345198389196/?active_tab=discussion)
+ Inscrições Django Girls (https://djangogirls.org/fortaleza/)

- [x] 29/03 | Debate sobre proteção de dados (É hoje!)
+ Cripto.Baião (É amanhã!)

**Comment by uira** [comment]
@dinamatias7 - [ ] @Dinamatias7 e @Vane_Cabral se inscreverem no DjangoGirls pra manjarem os paranauê de programação.

**Comment by dina-matias** [comment]
Vou me inscrever
